### ISSUE TITLE
Bug: cannot break lines in sheet

### ISSUE THREAD

**Issue by Bisstocuz** [YiGu-Studio/DocsModdingBannerlordCN#33]
表格中无法对文本进行换行操作
两个空格、\<br\>、\<br /\>均无法生效

**Comment by WuZhuoran** [comment]
#39 这个 PR之后 是否可以考虑试一试 加入 {{raw-html}} 这个 tag在 表格里面？ @Bisstocuz

**Comment by Bisstocuz** [comment]
After #39 , this issue can be fixed by using {{\< raw-html \>}}.
