### ISSUE TITLE
Please Add You as Contributor Here

### ISSUE THREAD

**Issue by WuZhuoran** [YiGu-Studio/DocsModdingBannerlordCN#7]
Hello, for all contributor, you can easily add you as a contributor in [README](https://github.com/YiGu-Studio/DocsModdingBannerlordCN/blob/main/README.md) via [all-contributors](https://allcontributors.org/)

If you already make some contribution, you can type the following comment in this issue. 
`all-contributors` will take care the rest part. No need to create a new issue. You can just type command here.

```
@all-contributors bot Please Add [@your account] for [what you did]
```

`your account` is like @WuZhuoran 
`what you did` is from this list [Contribution Types](https://allcontributors.org/docs/en/emoji-key)

Most common `Contribution Types` are: `bug`, `code`, `design`, `doc` and so on. You can also easily follow all the examples in this issue. If you are a translator, please add `translation` as your Type.

We welcome all kinds of contribution! Thank you!

大家好，如果你为本项目做过贡献，你可以非常简单的通过 [all-contributors](https://allcontributors.org/) 把你的名字加在我们 [项目简介](https://github.com/YiGu-Studio/DocsModdingBannerlordCN/blob/main/README.md) 的 `Contributor` 部分。

如果你已经提交过并通过了任何 Pull Request，你可以在本 Issue 下的评论部分使用如下命令。然后 `all-contributors` 将会处理剩下的事。不需要创建新的 Issue，直接在评论即可。

```
@all-contributors bot Please Add [@your account] for [what you did]
```
`your account` 可以是 @WuZhuoran 
`what you did` 可以从这个list中获取 [Contribution Types](https://allcontributors.org/docs/en/emoji-key)

一般常用的 `贡献类型` 包括：`bug`, `code`, `design`, `doc` 等，你可以参考本 Issue 下的所有 example。如果你参与了翻译，请使用 `translation` 类型。

欢迎各位的贡献！谢谢！

**Comment by WuZhuoran** [comment]
@all-contributors bot Please Add @WuZhuoran for code, translation

**Comment by Bisstocuz** [comment]
@all-contributors bot Please Add @Bisstocuz for translation, review

**Comment by Bisstocuz** [comment]
@all-contributors bot Please Add @Hallavan for translation

**Comment by WuZhuoran** [comment]
@all-contributors bot Please Add @Yuxuan1993  for translation

**Comment by tanjiarui15** [comment]
@all-contributors bot Please Add  @tanjiarui15  for translation

**Comment by WuZhuoran** [comment]
Please contribute to https://github.com/TaleWorlds/Documentations
